### ISSUE TITLE
Scrollback SIGSEGV bug

### ISSUE THREAD

**Issue by kevr** [chjj/st#1]
Hi. On Gnome while running st, if I have a scrollback log to use, resize the window, and start scrolling back, I get a SIGSEGV from st.

**Comment by kevr** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555559680 in xdraws (s=0x7fffffff941a "", x=<optimized out>, 
    y=<optimized out>, charlen=22, bytelen=20, base=...) at st.c:3551
3551            XftDrawStringUtf8(xw.draw, fg, frc[frp].font,
(gdb) bt
#0  0x0000555555559680 in xdraws (s=0x7fffffff941a "", x=<optimized 
out>, 
    y=<optimized out>, charlen=22, bytelen=20, base=...) at st.c:3551
#1  0x000055555555abbb in drawregion (y1=<optimized out>, x2=123, y2=42, 
x1=0)
    at st.c:3716
#2  0x000055555555b278 in draw () at st.c:3681
#3  0x000055555555b336 in redraw (timeout=0) at st.c:3668
#4  0x000055555555dbe6 in bpress (e=0x7fffffffe5e0) at st.c:986
#5  0x000055555555d259 in run () at st.c:4834
#6  0x00005555555578bf in main (argc=<optimized out>, argv_=<optimized 
out>)
    at st.c:4956
```

Here's a backtrace I collected from GDB with -g
